/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef skip_TYPES_H
#define skip_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace database_service {

class ret;

typedef struct _ret__isset {
  _ret__isset() : msg(false) {}
  bool msg :1;
} _ret__isset;

class ret : public virtual ::apache::thrift::TBase {
 public:

  ret(const ret&);
  ret& operator=(const ret&);
  ret() noexcept
      : msg() {
  }

  virtual ~ret() noexcept;
  std::string msg;

  _ret__isset __isset;

  void __set_msg(const std::string& val);

  bool operator == (const ret & rhs) const
  {
    if (!(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const ret &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ret & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(ret &a, ret &b);

std::ostream& operator<<(std::ostream& out, const ret& obj);

} // namespace

#endif
